### PR TITLE
upgrade version of javassist

### LINKED ISSUE #619: Error in running tests on Ubuntu
I get an error under both Java 7 and Java 8 when running `mvn test` in Ubuntu 15.04:

```
com.rackspacecloud.blueflood.service.BluefloodServiceStarterTest  Time elapsed: 0.794 sec  <<< ERROR!
java.lang.IllegalStateException: Failed to transform class with name com.rackspacecloud.blueflood.service.BluefloodServiceStarter. Reason: java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1090)
	at javassist.bytecode.ConstPool.read(ConstPool.java:1033)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:149)
	at javassist.bytecode.ClassFile.read(ClassFile.java:764)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:108)
	at javassist.CtClassType.getClassFile2(CtClassType.java:190)
	at javassist.CtClassType.subtypeOf(CtClassType.java:303)
	at javassist.CtClassType.subtypeOf(CtClassType.java:318)
	at javassist.compiler.MemberResolver.compareSignature(MemberResolver.java:247)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:119)
	at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:96)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:704)
	at javassist.expr.NewExpr$ProceedForNew.setReturnType(NewExpr.java:243)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:146)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:45)
	at javassist.compiler.TypeChecker.atVariableAssign(TypeChecker.java:248)
	at javassist.compiler.TypeChecker.atAssignExpr(TypeChecker.java:217)
	at javassist.compiler.ast.AssignExpr.accept(AssignExpr.java:38)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:241)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:329)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:350)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:404)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:354)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:49)
	at javassist.compiler.Javac.compileStmnt(Javac.java:568)
	at javassist.expr.NewExpr.replace(NewExpr.java:206)
	at org.powermock.core.transformers.impl.MainMockTransformer$PowerMockExpressionEditor.edit(MainMockTransformer.java:428)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:211)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:90)
	at javassist.CtClassType.instrument(CtClassType.java:1384)
	at org.powermock.core.transformers.impl.MainMockTransformer.transform(MainMockTransformer.java:75)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:203)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:145)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:439)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:420)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotations(Class.java:3446)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.classAnnotations(PowerMockJUnit44RunnerDelegateImpl.java:163)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getDescription(PowerMockJUnit44RunnerDelegateImpl.java:155)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:118)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
```

My Java versions:

```
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```

and

```
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```

### PR DESCRIPTION
**Pull request by shintasmith**
This should fix #619

### CODE REVIEW

**Comment by shintasmith** [comment]
@usnavi @ChandraAddala @VinnyQ pls review. I got a hint of the fix from this:
http://stackoverflow.com/questions/30313255/reflections-java-8-invalid-constant-type

**Comment by shintasmith** [comment]
cc: @izrik

**Comment by VinnyQ** [comment]
:+1: 
@shintasmith we won't know if this fix in ubuntu until someone runs it there?

**Comment by shintasmith** [comment]
@VinnyQ , yes, that's correct. I don't have an Ubuntu dev setup. But I got that same error running on my Mac before the changes. After the changes, it's gone.

**Comment by uhoh-itsmaciek** [comment]
Thanks for the quick fix. This resolves the issue for me, too.

**Comment by shintasmith** [comment]
yay!

**Pull request merged**
