### PR TITLE
Removing blueflood-kafka & blueflood-udp projects as they aren't used anymore.

### PR DESCRIPTION
**Pull request by usnavi**
```blueflood-kafka``` and ```blueflood-udp``` aren't used so we are removing them from the codebase so all existing code is relevant.

### CODE REVIEW

**Comment by ChandraAddala** [comment]
I dont know what these projects do but blueflood-kafka sounds like something we might look into in the future. Should we keep it?

**Comment by usnavi** [comment]
We'll still have the code in github, but having projects which aren't used and maintained is confusing for people looking at the codebase.

**Comment by usnavi** [comment]
@shintasmith @VinnyQ @ChandraAddala  - may i merge?

**Comment by ChandraAddala** [comment]
Go for it.

**Pull request merged**
