### PR TITLE
Removing value checks to ROR tests until we can investigate with CMD-1001

### PR DESCRIPTION
**Pull request by usnavi**

### CODE REVIEW

**Comment by ChandraAddala** [comment]
slacker!

**Comment by shintasmith** [comment]
@usnavi another test is failing

**Comment by usnavi** [comment]
@shintasmith - hmmm, this is more concerning.  Even though this is called "MultiRollupsQuery" this isn't verifying the generated values like the tests I added.  This is something that has been around for a while.

**Comment by usnavi** [comment]
@VinnyQ @izrik @ChandraAddala @shintasmith - welp, this ran 3 times on travis without failing.  (Boy that's confident!)

**Comment by ChandraAddala** [comment]
Looks good.

**Pull request merged**
