### PR TITLE
New: added requirements.txt for python demo

### PR DESCRIPTION
**Pull request by Dogild**

### CODE REVIEW

**Comment by stackedsax** [comment]
Seems totally reasonable.  Thanks for the PR.

It's funny, though, I recently wrote a bunch of documentation that totally uses files from the demo directory but I have never myself run the demo.  Would it be useful for me to write up something for this demo?  Did you find it useful to go through, @Dogild ?

Also, I know we use `requests` in this demo, but do we need `wsgiref`?

**Comment by usnavi** [comment]
Would @tilogaat @GeorgeJahad @drenalin23 mind looking at this and accepting if appropriate?

**Comment by Dogild** [comment]
@stackedsax The demo is useful ! What I would suggest is to make a demo with a UDP module as well, you don't find a lot of informations with the documentation on this point.

Other point, for this kind of project, people like to see some performance results etc etc...Maybe you could include a locust file (http://locust.io) to show how are the performance of your ReST API. Actually everybody do that when trying different technologies.

For the wsgiref, I did a pip freeze, I maybe messed up one of my virtualenv, let me correct that !

**Comment by stackedsax** [comment]
+1

**Pull request merged**
