### PR TITLE
Added deploy condition on jdk type

### PR DESCRIPTION
**Pull request by goru97**

### CODE REVIEW

**Comment by VinnyQ** [comment]
@goru97 why is this needed?

**Comment by tilogaat** [comment]
@goru97 @VinnyQ i think this is a part of the project to automatically push out builds. It only creates one build for Oracle java and not openjdk

**Comment by tilogaat** [comment]
@goru97 Can you confirm that's what it does?

**Comment by goru97** [comment]
@VinnyQ @tilogaat Previously after adding my changes to travis.yml, travis was creating uber jar whenever there was a push to rax-release branch and tried to deploy it in releases. Because there were two build processes running under different java environment (oracle jdk & open jdk), the first one to complete the build process was able to deploy it and second one failed because there was already a build deployed with matching tag. So to take care of this problem I added this condition as @tilogaat explained: it will only deploy for environment with oraclejdk.

**Comment by tilogaat** [comment]
+1

**Pull request merged**
