### PR TITLE
Adding --info flag to bf-rollup-delay.py for debugging

### PR DESCRIPTION
**Pull request by usnavi**
For a giving resolution:
- prints out unrolled slots & timestamps for all shards
- prints out last rolled up slot for all shards & timestamps for all shards

### CODE REVIEW

**Comment by shintasmith** [comment]
If it's debugging output, why is it called ```--info``` ? How about ```--printUnrolledSlots``` and ```--printLastRolledSlots``` ?

**Comment by usnavi** [comment]
I was thinking about ```--debugInfo``` but thought that was redundant.  I figure the tool is so narrow in its scope that the addition data merely expands on it that; a more specific flag doesn't really add value.  We'll see what @ChandraAddala or @VinnyQ @drenalin23 say.  ```---moreInfo```???

**Comment by shintasmith** [comment]
Maybe ```--verbose``` ?

**Comment by usnavi** [comment]
i like ```--verbose```

**Comment by ChandraAddala** [comment]
+1

**Comment by usnavi** [comment]
@shintasmith - now i'm verbose, in talk as well.

**Comment by shintasmith** [comment]
lgtm

**Pull request merged**
