### PR TITLE
Refactor bundle

### PR DESCRIPTION
**Pull request by VinnyQ**
* Rename Bundle class to AggregatedPayload.

* Extract and rename static classes in AggregatedPayload to com.rackspacecloud.blueflood.types
    -- extract class Counter and rename to BluefloodCounter
    -- rename CounterRollup to BluefloodCounterRollup
    -- extract class Gauge and rename to BluefloodGauge
    -- rename GaugeRollup to BluefloodGaugeRollup
    -- extract class Percentile
    -- extract class Timer and rename to BluefloodTimer
    -- rename TimerRollup to BluefloodTimerRollup
    -- extract class Set and rename to BluefloodSet
    -- Rename SetRollup to BluefloodSetRollup

### CODE REVIEW

**Comment by VinnyQ** [comment]
@tilogaat @GeorgeJahad please review.

PR for story https://jira.rax.io/browse/CMD-697

**Comment by tilogaat** [comment]
@VinnyQ 

Changes look good. I would love it if you renamed the classes to BluefloodSet, BluefloodGauge etc to make it clear that these types are specifically in the context of Blueflood.

**Comment by VinnyQ** [comment]
@tilogaat @GeorgeJahad 
Are you guys ok with the name "AggregatedPayload" for the Bundle class to be renamed to?

And also, do you want the extracted to be called BluefloodSet, BluefloodGauge, BluefloodCounter, BluefloodEnum, etc?  Or maybe a shorter version of "BfSet", "BfGauge", "BfCounter", "BfEnum", etc?

**Comment by tilogaat** [comment]
I am ok with the names suggested. BluefloodSet seems better :)

**Comment by VinnyQ** [comment]
Header added.  @GeorgeJahad @tilogaat please review and merge if all good.

**Pull request merged**
