### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by mburns**
# What

This refactors the Docker and Docker Compose files, moves them to the top level of the repo and tries to simplify the onboarding. The goal is to make using blueflood (as a dev onboarding or as a production operator) through a well-test Docker stack.

# Why

Having the files in the top-level conforms to the default paths for `docker` and `docker-compose`, which is (mildly) convenient.

Ops would like to manage Blueflood (along with the rest of MMI) in production through Docker, so we're trying to get some consistency in place early. This should also aid in simplifying the `branch`ing/environment process we currently use for Blueflood, as PR's can build docker images tied to a feature-change in Blueflood that can be deployed to various environments for testing.

# TODO
- [x] combine docker compose files (with and without `graphite-api`)
- [x] Ubuntu 12 base image is used in the `demo/` dir
- [x] pom build step, outputs to `build/` which is ignored by git.
- [ ] CIT Jenkins publishes changes to `Dockerfile`
- [ ] simplify `entrypoint.sh` logic
  * combine with `bin/blueflood-start.sh`?
- [ ] consolidate various `Dockerfile` and `docker-compose*.yml` files throughout the repo

### CODE REVIEW

**Comment by goru97** [comment]
👎

**Comment by mburns** [comment]
@goru97 that is not thoughtful feedback. try again.

**Comment by mburns** [comment]
I've changed back `docker-entrypoint.sh`, though I'm not a fan. The purpose of that shell script is broader than just Docker, but I'm fine with maintaining consistency.

As for Docker Hub, since we use manual build/upload, the `short description` and `long description` on hub.docker.com is already being managed manually (not synced with the nested  `README.md`).

**Comment by goru97** [comment]
👍 for the changes so far.

**Pull request closed without merging**
