### PR TITLE
feat(add-auth-to-es): Add authentication to elastic search connector

### PR DESCRIPTION
**Pull request by kaustavha**
This PR attempts to add authentication to the ES transport connector thingy so it can work with SaaS ES providers like ObjectRocket.

This PR is still very WIP, please don't merge.

### CODE REVIEW

**Comment by kaustavha** [comment]
BluefloodServiceStarterTest seems to fail no matter what.

**Comment by kaustavha** [comment]
Cleaned up & added more robust url handling to elasticIO service. Perhaps unit tests would be nice. 
Reviews welcome, still WIP though so please dont merge.

**Comment by shintasmith** [comment]
@kaustavha , we are having issues with Travis CI. Someone in our team is looking into it.

**Comment by usnavi** [comment]
@kaustavha  - the issue with travis is fixed.  Please rebase to add the fix to your branch and cause travis to rerun the build.

**Comment by kaustavha** [comment]
Should perhaps refactor how we setup ESsetup for all these tests but for the time being lets see if the patches work.
BluefloodServiceStarterTest continues to fail on local
` grabs popcorn and watches CI`

**Comment by kaustavha** [comment]
-1
cc @goru97 
This pr is nice, and allows BF to auth and use ES instances with any kinda normal auth set up using shield or any other fairly common username:password => base64 auth scheme which can be used using `curl -u` but considering we wont be demoing this using ES as a SaaS  at elasticon its kinda pointless. 

But the tests pass and im like 90% sure theres no accidentally left over dev code.

Let me know if I should rebase or make any changes or just close this PR.

**Comment by usnavi** [comment]
@shintasmith  @ChandraAddala @VinnyQ @izrik - I'm thinking that if there is no longer a need for this PR, we just close it.  What do you all think?

**Comment by izrik** [comment]
@usnavi It has merge conflicts and makes significant changes to pom files. If we don't need it, I vote we just close it. Good work, though.

**Pull request closed without merging**
