### PR TITLE
Doing some New Years' housecleaning

### PR DESCRIPTION
**Pull request by stackedsax**
This time, to create a PR....

### CODE REVIEW

**Comment by goru97** [comment]
LGTM :+1:

**Comment by stackedsax** [comment]
Sadly, I now realize that our tests depend on that load.script.  

I'll have to back out that change and figure out what we want to do there.  We clearly don't want to be dependent on cassandra-cli forever, since it disappears in Cassandra 2.1.1 or something around there.

**Comment by usnavi** [comment]
@stackedsax - shall we close this PR for now?

**Comment by stackedsax** [comment]
Yes, I'll close it.  I'll revisit this when I decide what to do.

**Pull request closed without merging**
