### PR TITLE
Removing old finder code

### PR DESCRIPTION
**Pull request by ChandraAddala**
We had placed the finder code into its own repository(https://github.com/rackerlabs/blueflood-graphite-finder) a while back and the current heat template uses the new repository. 

Removing the old code to avoid confusion.

### CODE REVIEW

**Comment by usnavi** [comment]
removing grinder or finder?  (see title) :-P

**Comment by ChandraAddala** [comment]
grinder, finder they are all same...

**Comment by VinnyQ** [comment]
👍  .. looks good, but are we certain no one is referencing this in their template/blog/scripts at the moment?

**Comment by shintasmith** [comment]
@ChandraAddala do we still need this change? If so, you'll need to rebase.

**Pull request merged**
